### ISSUE TITLE
Logout returning 400/500 error using old authentication

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#343]
When logged in to STAGE using the old login method, the API is returning a 400 error or sometimes a 500 error and only displaying the "Login with login.gov" button on the login screen. See screenshots below:
![image.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/baaf253f-e87a-4367-bdcc-530f099eaf11)
![unnamed.png](https://images.zenhubusercontent.com/61b9fc72d99b6f786e0d798c/58d30892-a01e-48d3-9899-76c202a9362f)

**Comment by MitchellTCG** [comment]
I got this error while logging out of Shelly's account
![Screenshot 2023-03-10 at 1.04.29 PM.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/874626d1-bbca-4804-a04b-9b561009dd5f)

**Comment by dheitzer** [comment]
the periodic 400 error was addressed with [this pull request ](https://github.com/fecgov/fecfile-web-app/pull/870).

**Comment by dheitzer** [comment]
reached out to Shelly to see if she has seen the 500 recently.  Currently unable to reproduce it.

**Comment by WiseQA** [comment]
@AureliaKhorsand @MitchellTCG @mjtravers Aurelia you had the same error, which we asked you update this ticket with findings beginning of week.   Not sure if she still getting this error.

**Comment by WiseQA** [comment]
@dheitzer I got the same logout error with FECfile as denoted above and the 500 error yesterday.

**Comment by dheitzer** [comment]
This 500 error can now be produced on demand:
1) go to https://fecfile-web-app-stage.app.cloud.gov/
2) login using legacy form
3) close the browser
4) open a new browser and go to https://fecfile-web-app-stage.app.cloud.gov/ (it should take you to the dashboard)
5) logout (this will show a 500 error)

Currently, the browser flag  login_dot_gov defaults to true.  This needs to be set to false.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review verified several times the following steps for the 400/500 error.

1.  go to https://fecfile-web-app-stage.app.cloud.gov/
2.  login using legacy form
3.  close the browser
4.  open a new browser and go to https://fecfile-web-app-stage.app.cloud.gov/ (it should take you to the dashboard)
5.  logout (No longer getting the 500 Server error)

**(Note both 400 / 500 error are not being displayed on both DEV and Stage environments.)**

QA Review Completed.   Moved to Stage Ready.
